/*
 *
 * Copyright (C) 2025-2026 Abdalla Bushnaq
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 *   Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 */

package de.bushnaq.abdalla.kassandra.dao;

import jakarta.persistence.*;
import lombok.*;

import java.time.LocalDate;

/**
 * JPA entity that persists the About Box banner image generated by Stable Diffusion.
 * <p>
 * The table holds exactly one row, always stored with {@code id = 1}. This singleton
 * pattern lets the application survive restarts without losing the last generated image:
 * {@link de.bushnaq.abdalla.kassandra.service.AboutBoxService} loads the stored bytes when
 * Stable Diffusion is unavailable and only regenerates when SD is reachable and the cached
 * date is stale.
 * </p>
 */
@Entity
@Table(name = "about_images")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString(callSuper = true)
@EqualsAndHashCode(of = {"id"}, callSuper = false)
public class AboutImageDAO extends AbstractTimeAwareDAO {

    /**
     * Singleton primary key – always {@code 1}. No {@code @GeneratedValue} because the
     * ID is assigned by the application, not by the database.
     */
    @Id
    @Column(name = "id")
    private Long id;
    /**
     * Raw PNG bytes of the 512×512 banner image produced by Stable Diffusion.
     */
    @Lob
    @Column(name = "image_data")
    private byte[] imageData;
    /**
     * The calendar date on which the stored image was generated.
     * Used to decide whether to regenerate the image the next day.
     */
    @Column(name = "image_date", nullable = false)
    private LocalDate imageDate;
}

