version: '3.8'

services:
  stable-diffusion:
    image: johnguan/stable-diffusion-webui
    container_name: kassandra-stable-diffusion
    ports:
      - "7861:7860"
    volumes:
      - ./models/Stable-diffusion:/data/models/Stable-diffusion
      - ./models/Lora:/data/models/Lora
      #- sd-outputs:/app/stable-diffusion-webui/outputs
    environment:
      # CLI arguments for the WebUI
      # Using SD 3 Medium model for better prompt adherence
      #- COMMANDLINE_ARGS=--api --xformers --medvram --no-half-vae --listen --port 8080 --skip-torch-cuda-test
      #- COMMANDLINE_ARGS=--api --xformers --no-half --no-half-vae --listen --port 8080 --skip-torch-cuda-test
      - COMMANDLINE_ARGS=--api --xformers --listen --port 7860
      # Set default model to SD 3 Medium
      - SD_MODEL=protovisionXLHighFidelity3D_beta0520Bakedvae.safetensors
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    restart: unless-stopped

